#! /bin/zsh

# tmp=$TMPDIR/x.sql
# sed -r "s/([^:])((:v\*)?:[-a-z?]+)/\1'\2--\3--XXXXX'/g" $1 >| $tmp
# pgsanity $tmp

# print 'in pglint'
print 'pgsanity called on file:' :: $0 :: $1 :: $2 :: ':end' >>/tmp/pgsanity.log

# Reads from stdin implicitly (as given by flymake), or single input file
sed -r "s/([^:])((:v\*)?:[-a-z?]+)/\1'\2--\3--XXXXX'/g" $1 | pgsanity

# rm $tmp
